### ISSUE TITLE
No Index.md included in sample

### ISSUE THREAD

**Issue by SimonDarksideJ** [NormandErwan/DocFxForUnity#22]
When cloning this sample and running "docfx documentation\docfx.json --serve", the generated site does not resemble what is shown on the example github pages site.

This seems to be because the Index.md that is mentioned in the docfx config is missing from the sample

**Comment by NormandErwan** [comment]
Apologies for the late answer. The `Documentation/index.md` is missing indeed because I copy it from `README.md`.

It's step 9 of the section [Setup your documentation](https://github.com/NormandErwan/DocFxForUnity#setup-your-documentation) in the readme.

It's also included in the [GitHub Action line 21](https://github.com/NormandErwan/DocFxForUnity/blob/main/.github/workflows/documentation.yml#L21).

I didn't want to maintain two files nor I found a way to synchronize them except by this manual copy.
